### PR TITLE
Use effect syntax for OCaml 5.3

### PR DESCRIPTION
**Pull request by avsm**
This currently needs https://github.com/ocaml/ocaml/pull/12309 (soon to be merged) and `opam pin add multicont --dev` as that also fails to compile with the released version.

### CODE REVIEW

**Comment by avsm** [comment]
This is expected to fail in ocaml-ci until https://github.com/ocaml/ocaml/pull/12309 is merged. You can try it out quickly by using `opam compiler '#12309'` to get an opam switch the PR included.

**Review by dhil — APPROVED** [review]
LFTM (looks familiar to me).

**Comment by dhil** [comment]
> [..] `opam pin add multicont --dev` as that also fails to compile with the released version.

Do you want me to prepare a new release?

**Comment by avsm** [comment]
@dhil a new release would be great! I think it's https://github.com/dhil/ocaml-multicont/pull/8 that is the problem, and you've merged that into your development tree.

**Comment by avsm** [comment]
It's green now in CI so I've gone ahead and merged this, and also added a note to the README that users who want a pre-effect-syntax can use the `5.1.1` tag instead.

**Pull request merged**
