### PR TITLE
Update to OCaml 5.1 in ci.yml

### PR DESCRIPTION
**Pull request by kayceesrk**

### CODE REVIEW

**Review by dhil — APPROVED** [review]

**Comment by kayceesrk** [comment]
I'm wondering why the CI keeps failing at multicont dependency. Would you know @dhil? CC @Sudha247.

**Comment by Sudha247** [comment]
My guess is that something is probably off with GitHub actions caches. Is it possible to reset it somehow? We used to fetch the later compiler commit, as a hack.

As as aside, since the jobs run on Ubuntu and macOS, can we enable ocaml-ci and retire this action?

**Comment by dhil** [comment]
No idea. I just updated the multicont repo to use OCaml 5.1.0. It was seemingly successful: https://github.com/dhil/ocaml-multicont/commit/35871d9c715a026ac2ce3c1ca4c6a78338202a88.

**Comment by Sudha247** [comment]
I went ahead and activated ocaml-ci. There are similar errors on some runs^^

**Comment by dhil** [comment]
I had another look at it. It seems like the header of `tbz` archive on the github release has been corrupted. I can try to recreate the `tbz` archive manually, but it will alter the hash. Will opam-repository let me fix the change hash on the package retrospectively? Or should I do a new release altogether?

**Comment by Sudha247** [comment]
@kit-ty-kate might know better (sorry for the ping!), but I think retroactive updates are accepted at opam-repository.

**Comment by dhil** [comment]
I have recompressed the archive and verified that I can extract with bzip2 now. I have opened a PR to change the hashes accordingly https://github.com/ocaml/opam-repository/pull/24586.

**Comment by Sudha247** [comment]
The CI is fine now, thanks @dhil. Linting tests are failing; @kayceesrk do you mind if I just run ocamlformat globally and push to this branch? I'm asking because the diff is rather huge.

**Comment by kayceesrk** [comment]
Sure. Go ahead.

**Pull request merged**
